// Login
export const GET_CUSTOMER_PROFILE = 'GET_CUSTOMER_PROFILE';

//Question
export const GET_LIST_GRADE_QUESTION = 'GET_LIST_GRADE_QUESTION';
export const GET_LIST_GROUP_QUESTION = 'GET_LIST_GROUP_QUESTION';
export const GET_LIST_STATUS_QUESTION = 'GET_LIST_STATUS_QUESTION';
export const GET_LIST_SUBJECT_QUESTION = 'GET_LIST_SUBJECT_QUESTION';
export const GET_LIST_CONTENT_QUESTION = 'GET_LIST_CONTENT_QUESTION';
export const GET_LIST_TYPE_QUESTION = 'GET_LIST_TYPE_QUESTION';
export const GET_QUESTION_DETAIL = 'GET_QUESTION_DETAIL';
export const GET_LIST_QUESTION = 'GET_LIST_QUESTION';
export const GET_COUNT_QUESTION = 'GET_COUNT_QUESTION';
